/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Default address space size. */
#define DEFAULT_ADDRESS_SPACE_SIZE 1024

/* Determine the block size */
#define FS_STAT_BLOCK_SIZE (m_stat.f_frsize)

/* Type of block count member in stat struct */
#define FS_STAT_COUNT_TYPE fsblkcnt_t

/* Function to determine filesystem stats from fd */
#define FS_STAT_FD fstatvfs(fd, &m_stat) == 0

/* Function to determine filesystem stats from filename */
#define FS_STAT_FN statvfs(fn, &m_stat) == 0

/* Type of block size member in stat struct */
#define FS_STAT_SIZE_TYPE unsigned long

/* Type of second argument to statfs function */
#define FS_STAT_STRUCT struct statvfs

/* true if config.h was included */
#define HAVE_CONFIG_H 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/mount.h> header file. */
/* #undef HAVE_SYS_MOUNT_H */

/* Define to 1 if you have the <sys/param.h> header file. */
/* #undef HAVE_SYS_PARAM_H */

/* Define to 1 if you have the <sys/statfs.h> header file. */
#define HAVE_SYS_STATFS_H 1

/* Define to 1 if you have the <sys/statvfs.h> header file. */
#define HAVE_SYS_STATVFS_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <sys/vfs.h> header file. */
#define HAVE_SYS_VFS_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Big endian */
/* #undef IS_BIG_ENDIAN */

/* Little endian */
#define IS_LITTLE_ENDIAN 1

/* Name of package */
#define PACKAGE "libtorrent"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "jaris@ifi.uio.no"

/* Define to the full name of this package. */
#define PACKAGE_NAME "libtorrent"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "libtorrent 0.10.4"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "libtorrent"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.10.4"

/* Identifier that is part of the default peer id */
#define PEER_NAME "-lt0A40-"

/* enable ipv6 stuff */
/* #undef RAK_USE_INET6 */

/* The size of a `long', as computed by sizeof. */
#define SIZEOF_LONG 4

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define this if the compiler supports the unused attribute */
#define SUPPORT_ATTRIBUTE_UNUSED 1

/* Require byte alignment */
/* #undef USE_ALIGNED */

/* Use epoll. */
#define USE_EPOLL 1

/* Enable extra debugging checks. */
/* #undef USE_EXTRA_DEBUG */

/* Enable kqueue. */
/* #undef USE_KQUEUE */

/* Use madvise */
#define USE_MADVISE 1

/* Use mincore */
#define USE_MINCORE 1

/* use char* in mincore */
#define USE_MINCORE_UNSIGNED 1

/* Using Mozilla's SHA1 implementation. */
/* #undef USE_NSS_SHA */

/* Using OpenSSL's SHA1 implementation. */
#define USE_OPENSSL_SHA 1

/* posix_fallocate supported. */
/* #undef USE_POSIX_FALLOCATE */

/* Version number of package */
#define VERSION "0.10.4"

/* Number of bits in a file offset, on hosts where this is settable. */
#define _FILE_OFFSET_BITS 64

/* Define for large files, on AIX-style hosts. */
/* #undef _LARGE_FILES */

/* Null-wrapper if unused attribute is unsupported */
#define __UNUSED __attribute__((unused))
